// frontoffice/src/components/layouts/image-viewer.component.jsx
import { Carousel } from '@mantine/carousel';
import { Image } from '@mantine/core';
import { useId } from 'react';

import { bufferToBase64 } from '@/utils/image';

export const ImageViewer = ({ images }) => {
  return (
    <Carousel mx="auto" loop withControls={images.length > 1} withIndicators={images.length > 1}>
      {images.map((image) => {
        const id = useId();

        return (
          <Carousel.Slide key={id}>
            <Image
              radius="md"
              src={`data:image/png;base64,` + bufferToBase64(image.content.data)}
              alt=""
            />
          </Carousel.Slide>
        );
      })}
    </Carousel>
  );
};

// game/src/components/ImageViewer.vue
<script setup>
import { bufferToBase64 } from '@app/helpers/image';

const props = defineProps(['image', 'alt']);
</script>

<template>
  <img
    v-if="image !== null"
    class="w-full h-full object-center object-cover rounded-t"
    :src="`data:image/png;base64,` + bufferToBase64(image?.content?.data)"
    :alt="alt"
  />
  <img
    v-else
    class="w-full h-full object-center object-cover rounded-t"
    src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
    alt=""
  />
</template>
